# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSubmittionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_email', models.EmailField(max_length=254)),
                ('verification_no', models.CharField(max_length=200)),
                ('share_id', models.CharField(max_length=200)),
                ('auth_code', models.CharField(max_length=200)),
                ('submittion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('submittion_status', models.CharField(max_length=200)),
                ('verification_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateVerificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=200)),
                ('document_name', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verifier_name', models.CharField(max_length=200)),
                ('verifier_email', models.EmailField(max_length=254)),
                ('verification_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('contact', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAlumniInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField()),
                ('contact', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('contact', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('verification_amount', models.IntegerField()),
                ('photo', models.ImageField(upload_to='university_logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=200, unique=True)),
                ('document_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to='documents')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.DocumentCategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.DocumentSubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=200)),
                ('verification_no', models.CharField(max_length=200, unique=True)),
                ('course', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('passing_date', models.DateField()),
                ('cgpa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('class_obtained', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('verifier_name', models.CharField(max_length=200)),
                ('verifier_email', models.EmailField(max_length=254)),
                ('verified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(max_length=200)),
                ('certificate', models.FileField(upload_to='verified_certificates')),
                ('institution_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.UniversityInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.StudentAlumniInfo')),
            ],
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='member',
            field=models.ManyToManyField(through='everify.UserDocuments', to='everify.DocumentSubcategory'),
        ),
        migrations.AddField(
            model_name='certificateverificationhistory',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.UserDocuments', to_field='document_id'),
        ),
        migrations.AddField(
            model_name='certificateverificationhistory',
            name='institution_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.UniversityInfo'),
        ),
        migrations.AddField(
            model_name='certificatesubmittionhistory',
            name='reference_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.VerifiedCertificates', to_field='verification_no'),
        ),
        migrations.AddField(
            model_name='certificatesubmittionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everify.StudentAlumniInfo'),
        ),
    ]
