# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everify', '0002_auto_20161130_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentalumniinfo',
            name='dateofbirth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
